# cSpell:disable
version: "2"

output:
  formats:
    text:
      path: stdout

linters:
  default: all
  disable:
    - gochecknoglobals
    - godot
    - noinlineerr
    - nlreturn
    - gomodguard
    - wsl
  enable:
    - gomodguard_v2
    - wsl_v5
  settings:
    depguard:
      rules:
        Main:
          allow:
            - $gostd
            - github.com/charmbracelet/bubbles
            - github.com/charmbracelet/bubbletea
            - github.com/charmbracelet/lipgloss
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
